name       : perl-dist-checkconflicts
version    : 0.11
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DO/DOY/Dist-CheckConflicts-0.11.tar.gz : ea844b9686c94d666d9d444321d764490b2cde2f985c4165b4c2c77665caedc4
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Dist::CheckConflicts - declare version conflicts for your dist
description: |
    Dist::CheckConflicts - declare version conflicts for your dist
builddeps  :
    - perl-module-runtime
    - perl-test-fatal
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
